### ISSUE TITLE
Feature Request: Provide alternate redirect URL on login() call

### ISSUE THREAD

**Issue by dbarkowsky** [bcgov/citz-imb-sso-express#45]
It would be nice to be able to supply a single-use redirect URL for login requests. 

Our current use case for this is to handle events when the user's token has expired and they are forced to log in again. Currently this action sends them back to the URL specified in the ENV.

**Comment by BradyMitch** [comment]
This is completely possible.

It would involve adding a property to LoginProps in the frontend for a redirectUrl.  
Then the backend login and loginCallback controllers would need to be updated to pass this parameter and modify the redirect url. We may need to have loginCallback pass this as a query param so that refresh_expires_in functionality is not affected. In that case, Wrapper in the frontend would need to be modified to redirect to this url.

I will add this to our backlog.

**Comment by BradyMitch** [comment]
Just testing out a new common code feature.

**Comment by BradyMitch** [comment]
Use version `1.0.0-alpha5` for this feature.
